services:
  app:
    container_name: back_end_pladonf
    build:
      context: .
      dockerfile: Dockerfile.java
    ports:
      - ${SPRING_PORT}:8000
    depends_on:
      mysqldb:
        condition: service_healthy
      init-keycloak:
        condition: service_completed_successfully
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_PORT=${KEYCLOAK_PORT}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    networks:
      - pladonf_api
      - pladonf_auth

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev --features=preview --import-realm --verbose
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_SERVER_ADDRESS: http://keycloak:8080
    ports:
      - ${KEYCLOAK_PORT}:8080
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json
    healthcheck:
      test: ["CMD", "/opt/keycloak/bin/kcadm.sh", "get", "realms/master", "--server", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - pladonf_auth

  init-keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    entrypoint: [ "/bin/sh", "/init-keycloak.sh" ]
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    volumes:
      - ./init-keycloak.sh:/init-keycloak.sh
    networks:
      - pladonf_auth

  mysqldb:
    image: mysql:8.2.0
    container_name: mysqldb_pladonf
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 10
      interval: 3s
      timeout: 30s
    networks:
      - pladonf_api
      - pladonf_auth

volumes:
  mysql-data:
  keycloak_data:
networks:
  pladonf_api:
    driver: bridge
  pladonf_auth:
    driver: bridge