package app.back.dto;

import jakarta.persistence.*;

@MappedSuperclass
public abstract class AutoGeneratedEntity<T extends AutoGeneratedEntity<T>> extends AbstractEntity<T> {

    @Override
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getId() {
        return super.getId();
    }

}
