package app.back.dto;

import jakarta.persistence.*;

@MappedSuperclass
public abstract class AutoGeneratedEntity extends AbstractEntity {

    @Override
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getId() {
        return super.getId();
    }

}
