package app.back.dto;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

@Entity
@Table(name = "discord_members")
public class DiscordMember extends AutoGeneratedEntity<DiscordMember> {

    @Column(name = "discordId", nullable = false)
    private Long discordId;

    @Column(name = "nickname")
    private String nickname;

    @Column(name = "firstname")
    private String firstname;

    public Long getDiscordId() {
        return discordId;
    }

    public void setDiscordId(Long discordId) {
        this.discordId = discordId;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Override
    public void write(DiscordMember dbEntity) {
        super.write(dbEntity);
        dbEntity.setDiscordId(discordId);
        dbEntity.setNickname(nickname);
        dbEntity.setFirstname(firstname);
    }

    @Override
    public String toString() {
        return "DiscordMember{" +
                "nickname='" + nickname + '\'' +
                ", firstname='" + firstname + '\'' +
                '}';
    }
}
