package app.back.dto;

import jakarta.persistence.*;

import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

@Entity
@Table(name = "events")
public class Event extends AutoGeneratedEntity<Event> {

    @Basic
    @Column(name = "eventName", nullable = false)
    private String eventName;

    @Basic
    @Column(name = "creationDate", nullable = false)
    private LocalDateTime creationDate = LocalDateTime.now();

    @Basic
    @Column(name = "startDate")
    private LocalDateTime startDate;

    @Basic
    @Column(name = "endDate")
    private LocalDateTime endDate;

    @Basic
    @Column(name = "location")
    private String location;

    @OneToMany(mappedBy = "parentEvent", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Event> subEvents;

    @ManyToOne
    private Event parentEvent;

    @ManyToMany
    @JoinTable(
            name = "discord_member_id",
            joinColumns = @JoinColumn(name = "participant_id"),
            inverseJoinColumns = @JoinColumn(name = "event_id")
    )
    private List<DiscordMember> participants;

    @ManyToMany
    @JoinTable(
            name = "todo_list_entries",
            joinColumns = @JoinColumn(name = "todo_entry_id"),
            inverseJoinColumns = @JoinColumn(name = "event_id")
    )
    private List<TodoListEntry> todoListEntries;

    @Column(name = "tricount")
    private String tricountUrl;

    public String getTricountUrl() {
        return tricountUrl;
    }

    public void setTricountUrl(String tricountUrl) {
        this.tricountUrl = tricountUrl;
    }

    public List<TodoListEntry> getTodoList() {
        return todoListEntries;
    }

    public void setTodoList(List<TodoListEntry> todoListEntries) {
        this.todoListEntries = todoListEntries;
    }

    public List<DiscordMember> getParticipants() {
        return participants;
    }

    public void setParticipants(List<DiscordMember> participants) {
        this.participants = participants;
    }

    public List<Event> getSubEvents() {
        return subEvents;
    }

    public void setSubEvents(List<Event> subEvents) {
        this.subEvents = subEvents;
    }

    public Event getParentEvent() {
        return parentEvent;
    }

    public void setParentEvent(Event parentEvent) {
        this.parentEvent = parentEvent;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public LocalDateTime getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDateTime endDate) {
        this.endDate = endDate;
    }

    public LocalDateTime getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDateTime startDate) {
        this.startDate = startDate;
    }

    public LocalDateTime getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(LocalDateTime creationDate) {
        this.creationDate = creationDate;
    }

    public String getEventName() {
        return eventName;
    }

    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    public Map<String, List<DiscordMember>> getTodoListMap() {
        Map<String, List<DiscordMember>> result = new HashMap<>();
        if(todoListEntries == null) {
            return result;
        }

        for (TodoListEntry entry : todoListEntries) {
            result.put(entry.getTodoValue(), entry.getDiscordMembers());
        }
        return result;
    }

    public List<TodoListEntry> setTodoListFromMap(Map<String, List<DiscordMember>> todoListMap) {
        if(todoListMap == null) {
            return new ArrayList<>();
        }

        this.todoListEntries = todoListMap.entrySet().stream().map(entry -> {
            var todo = entry.getKey();
            var discordMembers = entry.getValue();

            return new TodoListEntry(todo, discordMembers);
        }).collect(Collectors.toList());

        return this.todoListEntries;
    }

    @Override
    public void write(Event dbEntity) {
        super.write(dbEntity);
        dbEntity.setCreationDate(creationDate);
        dbEntity.setEventName(eventName);
        dbEntity.setLocation(location);
        dbEntity.setStartDate(startDate);
        dbEntity.setEndDate(endDate);
        dbEntity.setTricountUrl(tricountUrl);
        if(this.subEvents != null) {
            dbEntity.setSubEvents(subEvents);
        }
        if(this.participants != null) {
            dbEntity.setParticipants(participants);
        }
        if(this.todoListEntries != null) {
            dbEntity.setTodoList(todoListEntries);
        }
    }

    @Override
    public String toString() {
        return "Event{" +
                "eventName='" + eventName + '\'' +
                ", creationDate=" + creationDate +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                ", location='" + location + '\'' +
                ", subEvents=" + subEvents +
                ", participants=" + participants +
                ", todoListEntries=" + todoListEntries +
                ", tricountUrl='" + tricountUrl + '\'' +
                '}';
    }
}
