package app.back.dto;

import jakarta.persistence.*;

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "todos")
public class TodoEntry extends AutoGeneratedEntity {

    @Column(name = "todo")
    private String todoValue;

    @ManyToOne
    @JoinColumn(name = "discord_member_id")
    private Set<DiscordMember> discordMemberSet = new HashSet<>();
    
    public TodoEntry(String todoValue, Collection<DiscordMember> discordMemberSet) {
        this.todoValue = todoValue;
        this.discordMemberSet.addAll(discordMemberSet);
    }

    public String getTodoValue() {
        return todoValue;
    }

    public void setTodoValue(String todoValue) {
        this.todoValue = todoValue;
    }

    public Set<DiscordMember> getDiscordMembers() {
        return discordMemberSet;
    }

    public void setDiscordMemberSet(Collection<DiscordMember> discordMemberSet) {
        this.discordMemberSet.clear();
        this.discordMemberSet.addAll(discordMemberSet);
    }
}
