package app.back.dto;

import jakarta.persistence.*;

import java.util.List;

@Entity
@Table(name = "todos")
public class TodoListEntry extends AutoGeneratedEntity {

    @Column(name = "todo")
    private String todoValue;  // Clé de la Map

    @ManyToOne
    @JoinColumn(name = "discord_member_id")
    private List<DiscordMember> discordMember;

    public TodoListEntry() {

    }

    public TodoListEntry(String todoValue, List<DiscordMember> discordMember) {
        this.todoValue = todoValue;
        this.discordMember = discordMember;
    }

    public String getTodoValue() {
        return todoValue;
    }

    public void setTodoValue(String todoValue) {
        this.todoValue = todoValue;
    }

    public List<DiscordMember> getDiscordMembers() {
        return discordMember;
    }

    public void setDiscordMember(List<DiscordMember> discordMember) {
        this.discordMember = discordMember;
    }
}
