package app.back.dto;

import jakarta.persistence.*;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "todos")
public class TodoEntry extends AutoGeneratedEntity<TodoEntry> {

    @Column(name = "todo")
    private String todoValue;

    @ManyToOne
    @JoinColumn(name = "discord_member_id")
    private Set<DiscordMember> discordMember = new HashSet<>();

    public TodoEntry() {

    }

    public TodoEntry(String todoValue, Collection<DiscordMember> discordMember) {
        this.todoValue = todoValue;
        this.discordMember.addAll(discordMember);
    }

    @Override
    public void write(TodoEntry dbEntity) {
        super.write(dbEntity);
        dbEntity.discordMember = discordMember;
        dbEntity.todoValue = todoValue;
    }

    public String getTodoValue() {
        return todoValue;
    }

    public void setTodoValue(String todoValue) {
        this.todoValue = todoValue;
    }

    public Set<DiscordMember> getDiscordMembers() {
        return discordMember;
    }

    public void setDiscordMember(List<DiscordMember> discordMember) {
        this.discordMember.clear();
        this.discordMember.addAll(discordMember);
    }
}
